# -*- coding: utf-8 -*-
"""Comentarios_y_Opiniones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y09QBdNOTWWk8swPL7TJwhi4mYgePLex
"""
#LÓGICA JUAN
# Comentarios
def comentarios_opiniones():
    comentarios = []
    puntuaciones = []

    while True:
        comentario = input("Ingrese su comentario (o 'salir' para terminar): ")
        if comentario.lower() == 'salir':
            break

        # Solicitar puntuación
        while True:
            try:
                puntuacion = int(input("Puntuación de la página (1-5): "))
                if 1 <= puntuacion <= 5:
                    break
                else:
                    print("Por favor, ingrese un número entre 1 y 5.")
            except ValueError:
                print("Entrada no válida. Debe ser un número entre 1 y 5.")

        comentarios.append(comentario)
        puntuaciones.append(puntuacion)
        print("Comentario y puntuación registrados.")

    print("\n--- Comentarios y Opiniones Finales ---")
    for i in range(len(comentarios)):
        print(f"- Comentario: {comentarios[i]} | Puntuación: {'★' * puntuaciones[i]}{'☆' * (5 - puntuaciones[i])}")

# Llamada a la función
comentarios_opiniones()